/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BodyResetRouteImport } from './routes/body-reset'
import { Route as CoachingFuerZweiRouteImport } from './routes/coaching-fuer-zwei'
import { Route as DarmStoffwechselbegleitungRouteImport } from './routes/darm-stoffwechselbegleitung'
import { Route as DarmkurRouteImport } from './routes/darmkur'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ErnaehrungscoachingRouteImport } from './routes/ernaehrungscoaching'
import { Route as GoldeneGrundversorgungRouteImport } from './routes/goldene-grundversorgung'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as KatalogRouteImport } from './routes/katalog'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as MentalPerformanceRouteImport } from './routes/mental-performance'
import { Route as MetabolismRouteImport } from './routes/metabolism'
import { Route as MovementRouteImport } from './routes/movement'
import { Route as PerformanceTrainingRouteImport } from './routes/performance-training'
import { Route as SchmerzfreiRouteImport } from './routes/schmerzfrei'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as StoffwechselkurRouteImport } from './routes/stoffwechselkur'
import { Route as SystemStartRouteImport } from './routes/system-start'
import { Route as UeberMichRouteImport } from './routes/ueber-mich'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyResetRoute = BodyResetRouteImport.update({
  id: '/body-reset',
  path: '/body-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingFuerZweiRoute = CoachingFuerZweiRouteImport.update({
  id: '/coaching-fuer-zwei',
  path: '/coaching-fuer-zwei',
  getParentRoute: () => rootRouteImport,
} as any)
const DarmStoffwechselbegleitungRoute =
  DarmStoffwechselbegleitungRouteImport.update({
    id: '/darm-stoffwechselbegleitung',
    path: '/darm-stoffwechselbegleitung',
    getParentRoute: () => rootRouteImport,
  } as any)
const DarmkurRoute = DarmkurRouteImport.update({
  id: '/darmkur',
  path: '/darmkur',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ErnaehrungscoachingRoute = ErnaehrungscoachingRouteImport.update({
  id: '/ernaehrungscoaching',
  path: '/ernaehrungscoaching',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldeneGrundversorgungRoute = GoldeneGrundversorgungRouteImport.update({
  id: '/goldene-grundversorgung',
  path: '/goldene-grundversorgung',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const KatalogRoute = KatalogRouteImport.update({
  id: '/katalog',
  path: '/katalog',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const MentalPerformanceRoute = MentalPerformanceRouteImport.update({
  id: '/mental-performance',
  path: '/mental-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const MetabolismRoute = MetabolismRouteImport.update({
  id: '/metabolism',
  path: '/metabolism',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementRoute = MovementRouteImport.update({
  id: '/movement',
  path: '/movement',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceTrainingRoute = PerformanceTrainingRouteImport.update({
  id: '/performance-training',
  path: '/performance-training',
  getParentRoute: () => rootRouteImport,
} as any)
const SchmerzfreiRoute = SchmerzfreiRouteImport.update({
  id: '/schmerzfrei',
  path: '/schmerzfrei',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const StoffwechselkurRoute = StoffwechselkurRouteImport.update({
  id: '/stoffwechselkur',
  path: '/stoffwechselkur',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemStartRoute = SystemStartRouteImport.update({
  id: '/system-start',
  path: '/system-start',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberMichRoute = UeberMichRouteImport.update({
  id: '/ueber-mich',
  path: '/ueber-mich',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/body-reset': typeof BodyResetRoute
  '/coaching-fuer-zwei': typeof CoachingFuerZweiRoute
  '/darm-stoffwechselbegleitung': typeof DarmStoffwechselbegleitungRoute
  '/darmkur': typeof DarmkurRoute
  '/datenschutz': typeof DatenschutzRoute
  '/ernaehrungscoaching': typeof ErnaehrungscoachingRoute
  '/goldene-grundversorgung': typeof GoldeneGrundversorgungRoute
  '/impressum': typeof ImpressumRoute
  '/katalog': typeof KatalogRoute
  '/kontakt': typeof KontaktRoute
  '/mental-performance': typeof MentalPerformanceRoute
  '/metabolism': typeof MetabolismRoute
  '/movement': typeof MovementRoute
  '/performance-training': typeof PerformanceTrainingRoute
  '/schmerzfrei': typeof SchmerzfreiRoute
  '/sitemap': typeof SitemapRoute
  '/stoffwechselkur': typeof StoffwechselkurRoute
  '/system-start': typeof SystemStartRoute
  '/ueber-mich': typeof UeberMichRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/body-reset': typeof BodyResetRoute
  '/coaching-fuer-zwei': typeof CoachingFuerZweiRoute
  '/darm-stoffwechselbegleitung': typeof DarmStoffwechselbegleitungRoute
  '/darmkur': typeof DarmkurRoute
  '/datenschutz': typeof DatenschutzRoute
  '/ernaehrungscoaching': typeof ErnaehrungscoachingRoute
  '/goldene-grundversorgung': typeof GoldeneGrundversorgungRoute
  '/impressum': typeof ImpressumRoute
  '/katalog': typeof KatalogRoute
  '/kontakt': typeof KontaktRoute
  '/mental-performance': typeof MentalPerformanceRoute
  '/metabolism': typeof MetabolismRoute
  '/movement': typeof MovementRoute
  '/performance-training': typeof PerformanceTrainingRoute
  '/schmerzfrei': typeof SchmerzfreiRoute
  '/sitemap': typeof SitemapRoute
  '/stoffwechselkur': typeof StoffwechselkurRoute
  '/system-start': typeof SystemStartRoute
  '/ueber-mich': typeof UeberMichRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/body-reset': typeof BodyResetRoute
  '/coaching-fuer-zwei': typeof CoachingFuerZweiRoute
  '/darm-stoffwechselbegleitung': typeof DarmStoffwechselbegleitungRoute
  '/darmkur': typeof DarmkurRoute
  '/datenschutz': typeof DatenschutzRoute
  '/ernaehrungscoaching': typeof ErnaehrungscoachingRoute
  '/goldene-grundversorgung': typeof GoldeneGrundversorgungRoute
  '/impressum': typeof ImpressumRoute
  '/katalog': typeof KatalogRoute
  '/kontakt': typeof KontaktRoute
  '/mental-performance': typeof MentalPerformanceRoute
  '/metabolism': typeof MetabolismRoute
  '/movement': typeof MovementRoute
  '/performance-training': typeof PerformanceTrainingRoute
  '/schmerzfrei': typeof SchmerzfreiRoute
  '/sitemap': typeof SitemapRoute
  '/stoffwechselkur': typeof StoffwechselkurRoute
  '/system-start': typeof SystemStartRoute
  '/ueber-mich': typeof UeberMichRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/body-reset'
    | '/coaching-fuer-zwei'
    | '/darm-stoffwechselbegleitung'
    | '/darmkur'
    | '/datenschutz'
    | '/ernaehrungscoaching'
    | '/goldene-grundversorgung'
    | '/impressum'
    | '/katalog'
    | '/kontakt'
    | '/mental-performance'
    | '/metabolism'
    | '/movement'
    | '/performance-training'
    | '/schmerzfrei'
    | '/sitemap'
    | '/stoffwechselkur'
    | '/system-start'
    | '/ueber-mich'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/body-reset'
    | '/coaching-fuer-zwei'
    | '/darm-stoffwechselbegleitung'
    | '/darmkur'
    | '/datenschutz'
    | '/ernaehrungscoaching'
    | '/goldene-grundversorgung'
    | '/impressum'
    | '/katalog'
    | '/kontakt'
    | '/mental-performance'
    | '/metabolism'
    | '/movement'
    | '/performance-training'
    | '/schmerzfrei'
    | '/sitemap'
    | '/stoffwechselkur'
    | '/system-start'
    | '/ueber-mich'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/body-reset'
    | '/coaching-fuer-zwei'
    | '/darm-stoffwechselbegleitung'
    | '/darmkur'
    | '/datenschutz'
    | '/ernaehrungscoaching'
    | '/goldene-grundversorgung'
    | '/impressum'
    | '/katalog'
    | '/kontakt'
    | '/mental-performance'
    | '/metabolism'
    | '/movement'
    | '/performance-training'
    | '/schmerzfrei'
    | '/sitemap'
    | '/stoffwechselkur'
    | '/system-start'
    | '/ueber-mich'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  BodyResetRoute: typeof BodyResetRoute
  CoachingFuerZweiRoute: typeof CoachingFuerZweiRoute
  DarmStoffwechselbegleitungRoute: typeof DarmStoffwechselbegleitungRoute
  DarmkurRoute: typeof DarmkurRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ErnaehrungscoachingRoute: typeof ErnaehrungscoachingRoute
  GoldeneGrundversorgungRoute: typeof GoldeneGrundversorgungRoute
  ImpressumRoute: typeof ImpressumRoute
  KatalogRoute: typeof KatalogRoute
  KontaktRoute: typeof KontaktRoute
  MentalPerformanceRoute: typeof MentalPerformanceRoute
  MetabolismRoute: typeof MetabolismRoute
  MovementRoute: typeof MovementRoute
  PerformanceTrainingRoute: typeof PerformanceTrainingRoute
  SchmerzfreiRoute: typeof SchmerzfreiRoute
  SitemapRoute: typeof SitemapRoute
  StoffwechselkurRoute: typeof StoffwechselkurRoute
  SystemStartRoute: typeof SystemStartRoute
  UeberMichRoute: typeof UeberMichRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body-reset': {
      id: '/body-reset'
      path: '/body-reset'
      fullPath: '/body-reset'
      preLoaderRoute: typeof BodyResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching-fuer-zwei': {
      id: '/coaching-fuer-zwei'
      path: '/coaching-fuer-zwei'
      fullPath: '/coaching-fuer-zwei'
      preLoaderRoute: typeof CoachingFuerZweiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darm-stoffwechselbegleitung': {
      id: '/darm-stoffwechselbegleitung'
      path: '/darm-stoffwechselbegleitung'
      fullPath: '/darm-stoffwechselbegleitung'
      preLoaderRoute: typeof DarmStoffwechselbegleitungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darmkur': {
      id: '/darmkur'
      path: '/darmkur'
      fullPath: '/darmkur'
      preLoaderRoute: typeof DarmkurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ernaehrungscoaching': {
      id: '/ernaehrungscoaching'
      path: '/ernaehrungscoaching'
      fullPath: '/ernaehrungscoaching'
      preLoaderRoute: typeof ErnaehrungscoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goldene-grundversorgung': {
      id: '/goldene-grundversorgung'
      path: '/goldene-grundversorgung'
      fullPath: '/goldene-grundversorgung'
      preLoaderRoute: typeof GoldeneGrundversorgungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/katalog': {
      id: '/katalog'
      path: '/katalog'
      fullPath: '/katalog'
      preLoaderRoute: typeof KatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mental-performance': {
      id: '/mental-performance'
      path: '/mental-performance'
      fullPath: '/mental-performance'
      preLoaderRoute: typeof MentalPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metabolism': {
      id: '/metabolism'
      path: '/metabolism'
      fullPath: '/metabolism'
      preLoaderRoute: typeof MetabolismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movement': {
      id: '/movement'
      path: '/movement'
      fullPath: '/movement'
      preLoaderRoute: typeof MovementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance-training': {
      id: '/performance-training'
      path: '/performance-training'
      fullPath: '/performance-training'
      preLoaderRoute: typeof PerformanceTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schmerzfrei': {
      id: '/schmerzfrei'
      path: '/schmerzfrei'
      fullPath: '/schmerzfrei'
      preLoaderRoute: typeof SchmerzfreiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stoffwechselkur': {
      id: '/stoffwechselkur'
      path: '/stoffwechselkur'
      fullPath: '/stoffwechselkur'
      preLoaderRoute: typeof StoffwechselkurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-start': {
      id: '/system-start'
      path: '/system-start'
      fullPath: '/system-start'
      preLoaderRoute: typeof SystemStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-mich': {
      id: '/ueber-mich'
      path: '/ueber-mich'
      fullPath: '/ueber-mich'
      preLoaderRoute: typeof UeberMichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  BodyResetRoute: BodyResetRoute,
  CoachingFuerZweiRoute: CoachingFuerZweiRoute,
  DarmStoffwechselbegleitungRoute: DarmStoffwechselbegleitungRoute,
  DarmkurRoute: DarmkurRoute,
  DatenschutzRoute: DatenschutzRoute,
  ErnaehrungscoachingRoute: ErnaehrungscoachingRoute,
  GoldeneGrundversorgungRoute: GoldeneGrundversorgungRoute,
  ImpressumRoute: ImpressumRoute,
  KatalogRoute: KatalogRoute,
  KontaktRoute: KontaktRoute,
  MentalPerformanceRoute: MentalPerformanceRoute,
  MetabolismRoute: MetabolismRoute,
  MovementRoute: MovementRoute,
  PerformanceTrainingRoute: PerformanceTrainingRoute,
  SchmerzfreiRoute: SchmerzfreiRoute,
  SitemapRoute: SitemapRoute,
  StoffwechselkurRoute: StoffwechselkurRoute,
  SystemStartRoute: SystemStartRoute,
  UeberMichRoute: UeberMichRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
